version: '2.2'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1000m -Xmx1000m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  mysql-data:
    driver: local
  esdata:
    driver: local
